## Adding ConfigMap as volume
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
  labels:
    app: springboot
    app.kubernetes.io/part-of: springboot
    app.openshift.io/runtime: java
    app.kubernetes.io/name: java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: springbootdocker
        image: vipinpatel/springbootgit:latest
        args: 
          - /bin/sh 
          - -c
          - "echo 'hello world'"  ## adding Configmap As Volume Eg:- Kafka krb.conf files
        restartPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: env_name1
          value: local-dev
        resources:
          limits:
            cpu: "500m"
            memory: "250Mi"
          requests:
            cpu: "150m"
            memory: "250Mi"
        readinessProbe:
          httpGet:   
            path: /actuator/health/readiness
            port: 8080  
        livenessProbe: 
          httpGet:   
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 30   
        volumeMounts:
        - name: config-volume
          mountPath: /configmap
          readOnly: true
      volumes:
      - name: config-volume
        configMap: 
          name: springboot-configmap    