kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myclaim
  namespace: tribe-devops
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv0008
  volumeMode: Filesystem
status:
  phase: Bound
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
    - ReadOnlyMany
  capacity:
    storage: 100Gi